"""database

Revision ID: d3068fc6c94a
Revises: 
Create Date: 2021-05-30 01:18:00.348019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3068fc6c94a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_image', sa.String(length=50), nullable=True),
    sa.Column('about_header', sa.String(length=50), nullable=True),
    sa.Column('about_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beginner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beginner_title', sa.String(length=50), nullable=True),
    sa.Column('beginner_info', sa.String(length=100), nullable=True),
    sa.Column('beginner_image', sa.String(length=50), nullable=True),
    sa.Column('beginner_details', sa.String(length=50), nullable=True),
    sa.Column('beginner_link', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camps_title', sa.String(length=50), nullable=True),
    sa.Column('camps_info', sa.String(length=100), nullable=True),
    sa.Column('camps_image', sa.String(length=50), nullable=True),
    sa.Column('camps_details', sa.String(length=50), nullable=True),
    sa.Column('camps_link', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('column_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_header', sa.String(length=50), nullable=True),
    sa.Column('column_title', sa.String(length=50), nullable=True),
    sa.Column('column_text', sa.String(length=50), nullable=True),
    sa.Column('column_logo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_photo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galleryimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_src', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generic_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generic_title', sa.String(length=50), nullable=True),
    sa.Column('generic_text', sa.String(length=100), nullable=True),
    sa.Column('generic_image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=50), nullable=True),
    sa.Column('language_text', sa.String(length=50), nullable=True),
    sa.Column('language_image', sa.String(length=100), nullable=True),
    sa.Column('language_content', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(length=50), nullable=True),
    sa.Column('lesson_text', sa.String(length=50), nullable=True),
    sa.Column('lesson_url', sa.String(length=50), nullable=True),
    sa.Column('lesson_content', sa.String(length=50), nullable=True),
    sa.Column('lesson_logo', sa.String(length=50), nullable=True),
    sa.Column('lesson_details', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro_title', sa.String(length=50), nullable=True),
    sa.Column('pro_info', sa.String(length=100), nullable=True),
    sa.Column('pro_image', sa.String(length=50), nullable=True),
    sa.Column('pro_details', sa.String(length=50), nullable=True),
    sa.Column('pro_link', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sliderimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_src', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_icon', sa.String(length=50), nullable=True),
    sa.Column('social_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('social_media')
    op.drop_table('sliderimage')
    op.drop_table('pro')
    op.drop_table('lesson')
    op.drop_table('language')
    op.drop_table('generic_block')
    op.drop_table('galleryimage')
    op.drop_table('gallery')
    op.drop_table('column_control')
    op.drop_table('camps')
    op.drop_table('beginner')
    op.drop_table('about')
    # ### end Alembic commands ###
